name: supa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_screenutil: ^5.9.3
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.0+3
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ansicolor: ^2.0.3
  talker_dio_logger: ^4.4.1
  internet_connection_checker: ^1.0.0+1
  go_router: ^14.2.8
  email_validator: ^3.0.0
  formz: ^0.7.0
  string_validator: ^1.1.0
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansJP-SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
